openapi: 3.0.3
info:
  title: Support API
  version: 0.0.1
  description: |
    The Support API example spec.

servers:
  - url: http://localhost:8080/api/support
    description: Local development server
externalDocs:
  url: https://swagger.io/specification/
  description: Find more information about OAS3.0 standard.
tags:
  - name: Support
    description: API containing information about support services
paths:
  /: # don't forget to add the slash at the end. http://localhost:8080/api/rooms/
    get:
      operationId: getExample
      tags:
        - Support
      summary:  getExample summary
      description: getExample description
      responses:
        '200':
          description: getExample returns 200.
