openapi: 3.0.3
info:
  title: Support API
  version: 0.0.1
  description: |
    The Support API example spec.

servers:
  - url: http://localhost:8080/api/support
    description: Local development server
externalDocs:
  url: https://swagger.io/specification/
  description: Find more information about OAS3.0 standard.
tags:
  - name: Support
    description: API containing information about support services
paths:
  /dirty:
    get:
      operationId: getCleaningRequests
      tags:
        - Support
      summary: Query all requests for cleaning
      description: Collects all dirty and unassigned requests for cleaning and returns them as a list.
      responses:
        '200':
          description: Returned a list of cleaning requests.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Support'
  /{id}/start:
    parameters:
      - name: id
        in: path
        description: Room id
        required: true
        schema:
          type: integer
          minimum: 1
    post:
      operationId: createCleaningRequest
      tags:
        - Support
      summary: Create a cleaning request.
      description: Creates a cleaning request with a certain room Id
      requestBody:
        description: Checking object that needs to be added to the database.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Support'
      responses:
        '201':
          description: Cleaning request created.
        '400':
          description: Invalid input.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /{id}/end:
    parameters:
      - name: id
        in: path
        description: Room id
        required: true
        schema:
          type: integer
          minimum: 1
    put:
      operationId: endCleaningRequest
      tags:
        - Support
      summary: Finish a cleaning request.
      description: Finishes th cleaning request with a certain room Id
      requestBody:
        description: Checking object that needs to be edited to the database.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Support'
      responses:
        '201':
          description: Cleaning request finished.
        '400':
          description: Invalid input.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Support:
      type: object
      properties:
        requestId:
          type: integer
          description: Request ID.
          example: 0
          minimum: 0
        bookingId:
          type: integer
          description: Booking id
        assignedTo:
          type: integer
          description: ID of the person assigned to the cleaning task
        requestedAt:
          type: string
          format: date-time
          example: "2023-01-30T08:30:00Z"
          description: date and time of the request of cleaning
        cleanedAt:
          type: string
          format: date-time
          example: "2023-01-30T13:30:00Z"
          description: date and time of the end of cleaning
    Error:
      type: object
      properties:
        message:
          type: string
          description: Error message
        code:
          type: integer
          description: Error code
          minimum: 0
